"""empty message

Revision ID: 12eacf85c153
Revises: 
Create Date: 2021-05-22 20:15:51.937160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12eacf85c153'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_email', sa.String(length=64), nullable=True),
    sa.Column('receiver_email', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=16), nullable=True),
    sa.Column('clinic_name', sa.String(length=16), nullable=True),
    sa.Column('content', sa.String(length=64), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_clinic_name'), 'message', ['clinic_name'], unique=False)
    op.create_index(op.f('ix_message_content'), 'message', ['content'], unique=False)
    op.create_index(op.f('ix_message_fullname'), 'message', ['fullname'], unique=False)
    op.create_index(op.f('ix_message_receiver_email'), 'message', ['receiver_email'], unique=False)
    op.create_index(op.f('ix_message_sender_email'), 'message', ['sender_email'], unique=False)
    op.add_column('record', sa.Column('clinic_name', sa.String(length=16), nullable=True))
    op.add_column('record', sa.Column('status', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_record_clinic_name'), 'record', ['clinic_name'], unique=False)
    op.create_index(op.f('ix_record_status'), 'record', ['status'], unique=False)
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_index(op.f('ix_record_status'), table_name='record')
    op.drop_index(op.f('ix_record_clinic_name'), table_name='record')
    op.drop_column('record', 'status')
    op.drop_column('record', 'clinic_name')
    op.drop_index(op.f('ix_message_sender_email'), table_name='message')
    op.drop_index(op.f('ix_message_receiver_email'), table_name='message')
    op.drop_index(op.f('ix_message_fullname'), table_name='message')
    op.drop_index(op.f('ix_message_content'), table_name='message')
    op.drop_index(op.f('ix_message_clinic_name'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
