"""empty message

Revision ID: 66e2eac7ec19
Revises: 12eacf85c153
Create Date: 2021-05-22 21:41:10.055367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e2eac7ec19'
down_revision = '12eacf85c153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('request_limit', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_request_limit'), 'users', ['request_limit'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_request_limit'), table_name='users')
    op.drop_column('users', 'request_limit')
    # ### end Alembic commands ###
